GET http://localhost:3001/api/classes
###
POST http://localhost:3001/api/classes
Content-Type: application/json

{
    "name": "COM SCI 33"
}
###
POST http://localhost:3001/api/exchanges
Content-Type: application/json

{
    "finding": "PHYSICS 1A", 
    "exchanging": ["COM SCI 32", "COM SCI 31"], 
    "description": "everyday i wake up",
    "userId": "62d1fa5263971e4bf8583275"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root", 
    "password": "pass1" 
}