GET http://localhost:3001/api/classes
###
POST http://localhost:3001/api/classes
Content-Type: application/json

{
    "name": "COM SCI 33"
}
###
POST http://localhost:3001/api/exchanges
Content-Type: application/json

{
    "finding": "PHYSICS 1A", 
    "exchanging": ["COM SCI 32", "COM SCI 31"], 
    "description": "everyday i wake up",
    "userId": "62d1fa5263971e4bf8583275"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root", 
    "password": "pass1" 
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root", 
    "password": "pass1" 
}
###
POST http://localhost:3001/api/exchanges
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyZDFmYTUyNjM5NzFlNGJmODU4MzI3NSIsImlhdCI6MTY1ODA3MDczMn0.Ciq0GqseyN7msz8VUUDB2ySKjl-onnP3u6yyqrryw0M

{
    "finding": "MATH 61", 
    "exchanging": ["PHYSICS 1A", "COM SCI 31"], 
    "description": "everyday i wake up",
    "userId": "62d1706eebc276f98a3f31a2"
}