GET http://localhost:3001/api/classes
###
POST http://localhost:3001/api/classes
Content-Type: application/json

{
    "name": "COM SCI 33"
}
###
POST http://localhost:3001/api/exchanges
Content-Type: application/json

{
    "user": "1",
    "finding": "PHYSICS 1A", 
    "exchanging": ["COM SCI 32", "COM SCI 31"], 
    "description": "everyday i wake up"
}
###
POST http://localhost:3001/api/exchanges
Content-Type: application/json

{
    "username": "root", 
    "name": "user1",
    "password": "pass1" 
}